### ISSUE TITLE
Replace set-output with $GITHUB_OUTPUT

### ISSUE THREAD

**Issue by LRaulMendez** [zgosalvez/github-actions-get-flutter-version-env#9]
https://github.com/zgosalvez/github-actions-get-flutter-version-env/blob/db9a290316bd2032eb11b567bd68170455b76f98/dist/index.js#L52

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Examples
A workflow using `save-state` or `set-output` like the following

```
- name: Save state
  run: echo "::save-state name={name}::{value}"

- name: Set output
  run: echo "::set-output name={name}::{value}"
```

should be updated to write to the new `GITHUB_STATE `and `GITHUB_OUTPUT `environment files:

```
- name: Save state
  run: echo "{name}={value}" >> $GITHUB_STATE

- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT
```

**Comment by zgosalvez** [comment]
Thanks for the heads up, but this project isn't affected by the deprecation. The compiled index.js you found includes source code from GitHub's core action package that uses the deprecated code. The src index.js doesn't use it.
